backend:
  name: git-gateway
  repo: Bloom-Works/opo-dashboard
  branch: main

local_backend: true

media_folder: static/img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Main Page"
        name: "index"
        file: "src/pages/index.content.yml"
        fields:
          - label: Stats
            name: stats
            widget: object
            fields:
              - label: Stat 1
                name: stat1
                widget: object
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Value, name: value, widget: string }
              - label: Stat 2
                name: stat2
                widget: object
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Value, name: value, widget: string }
              - label: Stat 3
                name: stat3
                widget: object
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Value, name: value, widget: string }
          - label: Quote
            name: quote
            widget: object
            fields:
              - { label: Quote, name: quote, widget: string }
              - { label: Attribution, name: attribution, widget: string }
          - label: Video
            name: video
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: markdown }
              - { label: Link, name: link, widget: string }
